/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { scene } = useGLTF("./PORTFOLIO-v7_merch.glb");
  return <primitive object={scene} {...props} />;
}

useGLTF.preload("./PORTFOLIO-v7_merch.glb");
